---

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: ''

mysql_db:
     - name: autologic
       replicate: yes

mysql_users:
     - name: alogic
       pass: alogic
       priv: "*.*:ALL"
       host: "%"
mysql_db_id: 7
mysql_repl_role: master

mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION