---

- name: Copy NGINX nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy NGINX Hosts file
  copy:
    src: files/myhosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nginx
