---
- hosts: loadbalancer
  become: yes
  gather_facts: false
  roles:
    - role: common_utils
    - role: nginx
  post_tasks:
    - name: Check the AppName a page returns a status 200 and fail if the word WebApp1
      uri:
        url: http://loadbalancer/test
        return_content: yes
      register: this
      failed_when: "'webapp01' not in this.content"
    - name: Check the AppName a page returns a status 200 and fail if the word WebApp2
      uri:
        url: http://loadbalancer/test
        return_content: yes
      register: this
      failed_when: "'webapp02' not in this.content"

